version: '2'
services:
  flask:
    build:
      context: ./flask
  nginx:
    build:
      context: ./nginx
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt:ro
